import { jsPDF } from 'jspdf';

// ── Brand palette (Shri Aaum — light theme) ──────────────────────────────────
const BRAND = {
  gold:       [232, 168, 56],
  goldDark:   [192, 112, 48],
  goldLight:  [255, 243, 220],
  goldBg:     [252, 248, 240],
  white:      [255, 255, 255],
  textDark:   [40, 35, 30],
  textMed:    [100, 90, 75],
  textLight:  [140, 130, 115],
  tableBg1:   [255, 255, 255],
  tableBg2:   [252, 248, 240],
  tableHead:  [245, 235, 215],
  border:     [220, 205, 180],
  red:        [204, 51, 51],
};

const PLANET_SHORT = {
  Sun: 'Su', Moon: 'Mo', Mars: 'Ma', Mercury: 'Me',
  Jupiter: 'Ju', Venus: 'Ve', Saturn: 'Sa', Rahu: 'Ra', Ketu: 'Ke',
};

const PLANET_COLOR = {
  Sun: [200, 80, 16], Moon: [32, 80, 192], Mars: [192, 32, 32], Mercury: [26, 122, 72],
  Jupiter: [154, 112, 16], Venus: [176, 40, 136], Saturn: [58, 80, 112],
  Rahu: [160, 80, 32], Ketu: [90, 40, 128],
};

const SIGN_ORDER = [
  'Pisces','Aries','Taurus','Gemini','Cancer','Leo',
  'Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius',
];

const SIGN_SHORT = {
  Pisces:'Pis', Aries:'Ari', Taurus:'Tau', Gemini:'Gem',
  Cancer:'Can', Leo:'Leo', Virgo:'Vir', Libra:'Lib',
  Scorpio:'Sco', Sagittarius:'Sag', Capricorn:'Cap', Aquarius:'Aqu',
};

const SI_POSITIONS = {
  Pisces:[0,0], Aries:[1,0], Taurus:[2,0], Gemini:[3,0],
  Cancer:[3,1],                              Leo:[3,2],
  Virgo:[3,3], Libra:[2,3], Scorpio:[1,3], Sagittarius:[0,3],
  Capricorn:[0,2],                           Aquarius:[0,1],
};

// ── Helpers ───────────────────────────────────────────────────────────────────

function setColor(doc, rgb) { doc.setTextColor(rgb[0], rgb[1], rgb[2]); }
function setFill(doc, rgb)  { doc.setFillColor(rgb[0], rgb[1], rgb[2]); }
function setDraw(doc, rgb)  { doc.setDrawColor(rgb[0], rgb[1], rgb[2]); }

function drawPageHeader(doc, W) {
  setFill(doc, BRAND.gold);
  doc.rect(0, 0, W, 2.5, 'F');
  doc.setFontSize(9);
  setColor(doc, BRAND.gold);
  doc.text('Shri Aaum', W / 2, 10, { align: 'center' });
  doc.setFontSize(6);
  setColor(doc, BRAND.textLight);
  doc.text('Vedic Astrology & Kundli Services', W / 2, 14.5, { align: 'center' });
  setDraw(doc, BRAND.border);
  doc.setLineWidth(0.3);
  doc.line(14, 17, W - 14, 17);
}

function drawPageFooter(doc, W, H, pageNum) {
  const fy = H - 8;
  setDraw(doc, BRAND.border);
  doc.setLineWidth(0.2);
  doc.line(14, fy - 2, W - 14, fy - 2);
  doc.setFontSize(5.5);
  setColor(doc, BRAND.textLight);
  doc.text('Generated by Shri Aaum — shriaaum.com', 14, fy + 1);
  doc.text(`Page ${pageNum}`, W - 14, fy + 1, { align: 'right' });
}

function sectionTitle(doc, title, y, M) {
  setColor(doc, BRAND.goldDark);
  doc.setFontSize(10);
  doc.text(title, M, y + 4);
  setDraw(doc, BRAND.gold);
  doc.setLineWidth(0.5);
  doc.line(M, y + 6, M + 40, y + 6);
  return y + 12;
}

function drawTable(doc, headers, rows, colWidths, startX, startY, W, M) {
  const tableW = W - M * 2;
  let y = startY;

  setFill(doc, BRAND.tableHead);
  setDraw(doc, BRAND.border);
  doc.setLineWidth(0.2);
  doc.rect(startX, y, tableW, 6.5, 'FD');
  doc.setFontSize(6);
  setColor(doc, BRAND.goldDark);
  let cx = startX;
  headers.forEach((h, i) => {
    doc.text(h, cx + 2, y + 4.5);
    cx += colWidths[i];
  });
  y += 6.5;

  rows.forEach((row, idx) => {
    const bg = idx % 2 === 0 ? BRAND.tableBg1 : BRAND.tableBg2;
    setFill(doc, bg);
    setDraw(doc, BRAND.border);
    doc.setLineWidth(0.15);
    doc.rect(startX, y, tableW, 5.5, 'FD');
    doc.setFontSize(5.8);
    setColor(doc, BRAND.textDark);
    cx = startX;
    row.forEach((val, i) => {
      doc.text(String(val || ''), cx + 2, y + 4);
      cx += colWidths[i];
    });
    y += 5.5;
  });

  return y;
}

// ── Draw a small diamond shape (replacing ✦) ─────────────────────────────────
function drawDiamond(doc, cx, cy, r) {
  setFill(doc, BRAND.gold);
  setDraw(doc, BRAND.gold);
  doc.setLineWidth(0.2);
  const dx = r * 0.6;
  doc.lines(
    [[dx, r], [-dx, r], [-dx, -r]],
    cx, cy - r, [1, 1], 'F', true
  );
}

// ── North Indian Diamond Chart (PDF) ──────────────────────────────────────────

function drawNorthIndianChart(doc, housePlacements, retrogradeMap, degreeMap, ascDegree, x, y, size, title) {
  const m = size / 2;
  const cx = x + m;
  const cy = y + m;
  const s = size / 400;

  doc.setFontSize(7.5);
  setColor(doc, BRAND.goldDark);
  doc.text(title.toUpperCase(), cx, y - 4, { align: 'center' });

  setFill(doc, [248, 240, 216]);
  setDraw(doc, BRAND.gold);
  doc.setLineWidth(0.8);
  doc.rect(x, y, size, size, 'FD');

  // Diamond
  doc.setLineWidth(0.5);
  setDraw(doc, BRAND.gold);
  doc.line(cx, y, x + size, cy);
  doc.line(x + size, cy, cx, y + size);
  doc.line(cx, y + size, x, cy);
  doc.line(x, cy, cx, y);

  // Diagonals
  doc.setLineWidth(0.35);
  doc.line(x, y, cx, cy);
  doc.line(x + size, y, cx, cy);
  doc.line(x + size, y + size, cx, cy);
  doc.line(x, y + size, cx, cy);

  // Corner circles
  setFill(doc, BRAND.gold);
  [[x+1.5,y+1.5],[x+size-1.5,y+1.5],[x+size-1.5,y+size-1.5],[x+1.5,y+size-1.5]]
    .forEach(([px,py]) => doc.circle(px, py, 1.2, 'F'));

  const HNUM = {
    1:[295,30], 12:[362,95], 2:[200,55], 3:[105,30],
    4:[38,95], 5:[55,200], 6:[38,305], 7:[105,370],
    8:[200,345], 9:[295,370], 10:[362,305], 11:[345,200],
  };
  const PPOS = {
    1:[295,52], 12:[355,120], 2:[200,95], 3:[105,52],
    4:[45,120], 5:[95,200], 6:[45,280], 7:[105,348],
    8:[200,305], 9:[295,348], 10:[355,280], 11:[305,200],
  };

  doc.setFontSize(5.5);
  for (const [h, [hx,hy]] of Object.entries(HNUM)) {
    setColor(doc, BRAND.red);
    doc.text(h, x + hx*s, y + hy*s, { align: 'center' });
  }

  doc.setFontSize(4.5);
  setColor(doc, BRAND.goldDark);
  const ascLabel = 'Asc' + (ascDegree != null ? `-${Number(ascDegree).toFixed(2)}°` : '');
  doc.text(ascLabel, x + 295*s, y + 15*s, { align: 'center' });

  doc.setFontSize(5);
  for (let num = 1; num <= 12; num++) {
    const hp = housePlacements?.find(h => h.house === num);
    if (!hp?.planets?.length) continue;
    const [px,py] = PPOS[num];
    hp.planets.forEach((p, i) => {
      const color = PLANET_COLOR[p] || [80,80,80];
      setColor(doc, color);
      const name = PLANET_SHORT[p] || p.slice(0,2);
      const deg = degreeMap?.[p];
      const degStr = deg != null ? `-${Number(deg).toFixed(1)}°` : '';
      const retro = retrogradeMap?.[p] ? 'R' : '';
      doc.text(`${name}${degStr}${retro}`, x + px*s, y + py*s + i*3.5, { align: 'center' });
    });
  }
}

// ── South Indian Chart (PDF) ──────────────────────────────────────────────────

function drawSouthIndianChart(doc, planets, ascendantSign, retrogradeMap, degreeMap, x, y, size, title) {
  const cell = size / 4;

  doc.setFontSize(7.5);
  setColor(doc, BRAND.goldDark);
  doc.text(title.toUpperCase(), x + size/2, y - 4, { align: 'center' });

  setDraw(doc, BRAND.gold);
  doc.setLineWidth(0.8);
  doc.rect(x, y, size, size);

  const signPlanets = {};
  for (const [name, data] of Object.entries(planets || {}))
    if (!signPlanets[data.sign]) signPlanets[data.sign] = [name]; else signPlanets[data.sign].push(name);
  const ascIdx = SIGN_ORDER.indexOf(ascendantSign);

  for (const [sign, [col,row]] of Object.entries(SI_POSITIONS)) {
    const cx2 = x + col*cell, cy2 = y + row*cell;
    const isAsc = sign === ascendantSign;
    const idx = SIGN_ORDER.indexOf(sign);
    const house = (ascIdx !== -1 && idx !== -1) ? ((idx - ascIdx + 12) % 12) + 1 : null;

    doc.setLineWidth(0.4);
    setDraw(doc, BRAND.gold);
    setFill(doc, isAsc ? [255,248,230] : [248,240,216]);
    doc.rect(cx2, cy2, cell, cell, 'FD');

    doc.setFontSize(5.5);
    setColor(doc, BRAND.textMed);
    doc.text(SIGN_SHORT[sign] || sign.slice(0,3), cx2+2, cy2+5);

    if (house) { doc.setFontSize(5); setColor(doc, BRAND.textLight); doc.text(String(house), cx2+cell-4, cy2+5); }
    if (isAsc) { doc.setFontSize(4.5); setColor(doc, BRAND.goldDark); doc.text('Asc', cx2+cell/2, cy2+10, {align:'center'}); }

    const pList = signPlanets[sign] || [];
    doc.setFontSize(5);
    pList.forEach((p, i) => {
      const color = PLANET_COLOR[p] || [80,80,80];
      setColor(doc, color);
      const nm = PLANET_SHORT[p] || p.slice(0,2);
      const deg = degreeMap?.[p];
      const degStr = deg != null ? `-${Number(deg).toFixed(1)}°` : '';
      const retro = retrogradeMap?.[p] ? 'R' : '';
      doc.text(`${nm}${degStr}${retro}`, cx2+cell/2, cy2 + (isAsc ? 14 : 10) + i*3.5, {align:'center'});
    });
  }

  // Center — draw diamond instead of ✦
  setFill(doc, [252,248,238]);
  setDraw(doc, BRAND.gold);
  doc.setLineWidth(0.4);
  doc.rect(x+cell, y+cell, cell*2, cell*2, 'FD');
  drawDiamond(doc, x + size/2, y + size/2, 3);
}

// ── Load logo image ───────────────────────────────────────────────────────────

async function loadLogoBase64() {
  try {
    const resp = await fetch('/assets/logo.png');
    if (!resp.ok) return null;
    const ct = resp.headers.get('content-type') || '';
    if (!ct.startsWith('image/')) return null;
    const blob = await resp.blob();
    if (blob.size < 100) return null;
    return new Promise(resolve => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch { return null; }
}

// ── Main PDF export ───────────────────────────────────────────────────────────

export async function downloadKundliPdf(data) {
  const { report, kp, planets: rawPlanets } = data;
  if (!report) return;

  const {
    summary, housePlacements, planetaryStrengths,
    currentDasha, dashaTimeline, doshas, navamsha,
  } = report;

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210, H = 297, M = 14;

  const retrogradeMap = rawPlanets
    ? Object.fromEntries(Object.entries(rawPlanets).map(([n,p]) => [n, p.isRetrograde])) : {};
  const degreeMap = rawPlanets
    ? Object.fromEntries(Object.entries(rawPlanets).map(([n,p]) => [n, p.degree ?? (p.longitude % 30)])) : {};
  const ascDegree = data.ascendant?.degree ?? null;

  const bhavChality = kp ? (() => {
    const houses = Array.from({length:12}, (_,i) => ({house:i+1, sign:kp.cusps[i]?.sign||'', lord:'', planets:[]}));
    for (const [name,planet] of Object.entries(kp.kpPlanets)) {
      const h = planet.kpHouse; if (h>=1 && h<=12) houses[h-1].planets.push(name);
    }
    return houses;
  })() : null;

  const bhavChalitPlanetsForSouth = kp ? (() => {
    const result = {};
    for (const [name,kpPlanet] of Object.entries(kp.kpPlanets)) {
      const houseSign = kp.cusps[kpPlanet.kpHouse-1]?.sign || (rawPlanets?.[name]?.sign ?? '');
      result[name] = {...(rawPlanets?.[name]||{}), sign: houseSign};
    }
    return result;
  })() : null;

  // Try loading logo
  const logoData = await loadLogoBase64();

  let pageNum = 2;

  // ═══════════════════════════════════════════════════════════════════════════
  // PAGE 1 — Cover Page
  // ═══════════════════════════════════════════════════════════════════════════

  // Gold accent bar
  setFill(doc, BRAND.gold);
  doc.rect(0, 0, W, 3, 'F');

  // Logo
  let coverY = 16;
  let logoAdded = false;
  if (logoData) {
    try {
      doc.addImage(logoData, 'PNG', W/2 - 15, coverY, 30, 30);
      coverY += 36;
      logoAdded = true;
    } catch { /* logo failed, use text fallback */ }
  }
  if (!logoAdded) {
    doc.setFontSize(18);
    setColor(doc, BRAND.gold);
    doc.text('Shri Aaum', W/2, coverY + 8, {align:'center'});
    coverY += 16;
  }

  // Title
  doc.setFontSize(26);
  setColor(doc, BRAND.textDark);
  doc.text('Kundli Report', W/2, coverY + 6, {align:'center'});

  doc.setFontSize(9);
  setColor(doc, BRAND.textLight);
  doc.text('Vedic Birth Chart & Astrological Analysis', W/2, coverY + 14, {align:'center'});

  // Gold rule
  setDraw(doc, BRAND.gold);
  doc.setLineWidth(0.6);
  doc.line(W/2 - 35, coverY + 19, W/2 + 35, coverY + 19);

  // Name
  coverY += 30;
  doc.setFontSize(18);
  setColor(doc, BRAND.goldDark);
  doc.text(summary.name || '', W/2, coverY, {align:'center'});

  // Birth details card
  coverY += 10;
  const cardH = 55;
  setFill(doc, BRAND.goldBg);
  setDraw(doc, BRAND.border);
  doc.setLineWidth(0.3);
  doc.rect(M + 10, coverY, W - M*2 - 20, cardH, 'FD');

  // Gold top accent on card
  setFill(doc, BRAND.gold);
  doc.rect(M + 10, coverY, W - M*2 - 20, 1.5, 'F');

  const detailPairs = [
    ['Date of Birth',     summary.dateOfBirth],
    ['Time of Birth',     summary.timeOfBirth],
    ['Place of Birth',    summary.placeOfBirth],
    ['Ascendant (Lagna)', `${summary.ascendant} (${summary.ascendantLord})`],
    ['Moon Sign (Rashi)', `${summary.moonSign} (${summary.rashiLord})`],
    ['Sun Sign',          summary.sunSign],
    ['Birth Nakshatra',   `${summary.birthNakshatra} Pada ${summary.nakshatraPada}`],
    ['Nakshatra Lord',    summary.nakshatraLord],
  ];

  const cardX = M + 18, col2X = W/2 + 8;
  detailPairs.forEach(([label, val], i) => {
    const dx = i % 2 === 0 ? cardX : col2X;
    const dy = coverY + 7 + Math.floor(i/2) * 12.5;
    doc.setFontSize(5.5);
    setColor(doc, BRAND.textLight);
    doc.text(label.toUpperCase(), dx, dy);
    doc.setFontSize(8.5);
    setColor(doc, BRAND.textDark);
    doc.text(String(val || ''), dx, dy + 5);
  });

  // Bottom gold bar
  setFill(doc, BRAND.gold);
  doc.rect(0, H - 10, W, 10, 'F');
  doc.setFontSize(7);
  setColor(doc, BRAND.white);
  doc.text('shriaaum.com', W/2, H - 4, {align:'center'});

  // ═══════════════════════════════════════════════════════════════════════════
  // PAGE 2 — Charts
  // ═══════════════════════════════════════════════════════════════════════════
  doc.addPage();
  drawPageHeader(doc, W);
  let gy = 22;

  gy = sectionTitle(doc, 'North Indian Charts', gy, M);
  const chartSize = 80;
  drawNorthIndianChart(doc, housePlacements, retrogradeMap, degreeMap, ascDegree, M + 2, gy + 4, chartSize, 'Lagna Chart');
  if (bhavChality)
    drawNorthIndianChart(doc, bhavChality, retrogradeMap, degreeMap, ascDegree, M + chartSize + 14, gy + 4, chartSize, 'Bhav Chalit');
  gy += chartSize + 14;

  gy = sectionTitle(doc, 'South Indian Charts', gy, M);
  drawSouthIndianChart(doc, rawPlanets, summary.ascendant, retrogradeMap, degreeMap, M + 2, gy + 4, chartSize, 'Lagna Chart');
  if (bhavChalitPlanetsForSouth)
    drawSouthIndianChart(doc, bhavChalitPlanetsForSouth, summary.ascendant, retrogradeMap, degreeMap, M + chartSize + 14, gy + 4, chartSize, 'Bhav Chalit');

  drawPageFooter(doc, W, H, pageNum++);

  // ═══════════════════════════════════════════════════════════════════════════
  // PAGE 3 — Planetary Positions + Houses
  // ═══════════════════════════════════════════════════════════════════════════
  doc.addPage();
  drawPageHeader(doc, W);
  let py = 22;

  py = sectionTitle(doc, 'Planetary Positions', py, M);
  const planetHeaders = ['Planet', 'Sign', 'House', 'Degree', 'Nakshatra', 'Pada', 'Retro'];
  const planetColW = [24, 22, 15, 20, 30, 14, 14];
  const planetRows = planetaryStrengths.map(p => [
    p.planet, p.sign, String(p.house), `${p.degree?.toFixed(2)}°`,
    p.nakshatra, String(p.pada), p.isRetrograde ? 'R' : '—',
  ]);
  py = drawTable(doc, planetHeaders, planetRows, planetColW, M, py, W, M);

  py += 10;
  py = sectionTitle(doc, 'House Placements (Whole Sign)', py, M);
  const houseHeaders = ['House', 'Sign', 'Lord', 'Planets'];
  const houseColW = [20, 30, 25, 87];
  const houseRows = housePlacements.map(h => [
    `House ${h.house}`, h.sign, h.lord, h.planets.join(', ') || '—',
  ]);
  py = drawTable(doc, houseHeaders, houseRows, houseColW, M, py, W, M);

  drawPageFooter(doc, W, H, pageNum++);

  // ═══════════════════════════════════════════════════════════════════════════
  // PAGE 4 — KP System + Dasha
  // ═══════════════════════════════════════════════════════════════════════════
  if (kp) {
    doc.addPage();
    drawPageHeader(doc, W);
    py = 22;

    py = sectionTitle(doc, 'KP Ruling Planets', py, M);
    const rpData = [
      ['Ascendant', kp.rulingPlanets.ascSignLord, kp.rulingPlanets.ascStarLord, kp.rulingPlanets.ascSubLord],
      ['Moon', kp.rulingPlanets.moonSignLord, kp.rulingPlanets.moonStarLord, kp.rulingPlanets.moonSubLord],
      ['Day Lord', kp.rulingPlanets.dayLord, '', ''],
    ];
    rpData.forEach((card, ci) => {
      const cx = M + ci * 62;
      setFill(doc, BRAND.goldLight);
      setDraw(doc, BRAND.border);
      doc.setLineWidth(0.3);
      doc.rect(cx, py, 58, 16, 'FD');
      doc.setFontSize(7);
      setColor(doc, BRAND.goldDark);
      doc.text(card[0], cx+3, py+5);
      doc.setFontSize(5.5);
      setColor(doc, BRAND.textDark);
      doc.text(card[2] ? `Sign: ${card[1]}  Star: ${card[2]}  Sub: ${card[3]}` : card[1], cx+3, py+11);
    });
    py += 22;

    py = sectionTitle(doc, 'KP Planets', py, M);
    const kpHeaders = ['Planet', 'Sign', 'Degree', 'KP House', 'Nakshatra', 'Sign Lord', 'Star Lord', 'Sub Lord'];
    const kpColW = [20, 20, 16, 18, 26, 22, 22, 22];
    const kpRows = Object.values(kp.kpPlanets).map(p => [
      p.planet + (p.isRetrograde ? ' R' : ''), p.sign, `${p.degree?.toFixed(1)}°`,
      String(p.kpHouse), p.nakshatra, p.signLord, p.starLord, p.subLord,
    ]);
    py = drawTable(doc, kpHeaders, kpRows, kpColW, M, py, W, M);

    py += 10;
    py = sectionTitle(doc, 'Vimshottari Dasha Timeline', py, M);

    if (currentDasha) {
      setFill(doc, BRAND.goldLight);
      setDraw(doc, BRAND.gold);
      doc.setLineWidth(0.4);
      doc.rect(M, py, W - M*2, 14, 'FD');
      doc.setFontSize(9);
      setColor(doc, BRAND.goldDark);
      doc.text(`Current: ${currentDasha.mahadasha} Mahadasha`, M+4, py+6);
      doc.setFontSize(7);
      setColor(doc, BRAND.textMed);
      doc.text(
        `${currentDasha.antardasha ? currentDasha.antardasha+' Antardasha · ' : ''}${currentDasha.mahaStart} → ${currentDasha.mahaEnd}`,
        M+4, py+11.5
      );
      py += 18;
    }

    const dashaHeaders = ['Mahadasha Lord', 'Start', 'End', 'Duration'];
    const dashaColW = [45, 45, 45, 27];
    const dashaRows = (dashaTimeline||[]).slice(0,9).map(d => [d.lord, d.start, d.end, `${d.years?.toFixed(1)}y`]);
    py = drawTable(doc, dashaHeaders, dashaRows, dashaColW, M, py, W, M);

    drawPageFooter(doc, W, H, pageNum++);
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // PAGE 5 — Doshas + Navamsha
  // ═══════════════════════════════════════════════════════════════════════════
  doc.addPage();
  drawPageHeader(doc, W);
  py = 22;

  py = sectionTitle(doc, 'Doshas & Afflictions', py, M);

  const presentDoshas = doshas?.filter(d => d.present) || [];
  const noDoshas = doshas?.filter(d => !d.present) || [];

  presentDoshas.forEach(d => {
    doc.setFillColor(255, 240, 240);
    doc.setDrawColor(220, 120, 120);
    doc.setLineWidth(0.3);
    doc.rect(M, py, W - M*2, 20, 'FD');
    doc.setFontSize(8);
    doc.setTextColor(180, 50, 50);
    doc.text(d.name, M+4, py+5.5);
    doc.setFontSize(6);
    doc.setTextColor(180, 80, 80);
    doc.text(`Severity: ${d.severity}`, M+60, py+5.5);
    doc.setFontSize(5.5);
    setColor(doc, BRAND.textMed);
    const lines = doc.splitTextToSize(d.description || '', W - M*2 - 8);
    doc.text(lines.slice(0,2).join('\n'), M+4, py+11);
    if (d.remedy) { doc.setFontSize(5.5); setColor(doc, BRAND.goldDark); doc.text(`Remedy: ${d.remedy}`.substring(0,100), M+4, py+17.5); }
    py += 24;
  });

  if (noDoshas.length > 0) {
    doc.setFillColor(240, 255, 240);
    doc.setDrawColor(140, 200, 140);
    doc.setLineWidth(0.2);
    doc.rect(M, py, W - M*2, 7, 'FD');
    doc.setFontSize(6);
    doc.setTextColor(60, 140, 60);
    doc.text(`Not Present: ${noDoshas.map(d => d.name).join(', ')}`, M+4, py+4.5);
    py += 11;
  }

  py += 6;
  py = sectionTitle(doc, 'Navamsha Chart (D9)', py, M);
  const navHeaders = ['Planet', 'Navamsha Sign', 'Sign Lord'];
  const navColW = [45, 60, 60];
  const navRows = (navamsha||[]).map(n => [n.planet, n.navamshaSign, n.lord]);
  py = drawTable(doc, navHeaders, navRows, navColW, M, py, W, M);

  drawPageFooter(doc, W, H, pageNum++);

  // ── Save ──
  const safeName = (summary.name || 'Kundli').replace(/[^a-zA-Z0-9_]/g, '_');
  doc.save(`${safeName}-kundli-report.pdf`);
}
